# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gibbs Sampling for Exponential Distribution (Rcpp)
#'  @importFrom MASS glm
#'  @importFrom boot boot
#'  @importFrom DAAG cv.lm
#'  @importFrom bootstrap bootstrap
#'  @importFrom coda effectiveSize gelman.diag
#' @importFrom stats rgamma
#' @param y Numeric vector of observed data.
#' @param alpha Prior shape parameter for the Gamma distribution.
#' @param beta Prior rate parameter for the Gamma distribution.
#' @param n_iter Number of Gibbs sampling iterations.
#' @return A vector of sampled lambda values or the posterior mean if return_mean = TRUE.
gibbs_exponential_cpp <- function(y, alpha, beta, n_iter) {
    .Call(`_BL22204009_gibbs_exponential_cpp`, y, alpha, beta, n_iter)
}
#' Gibbs Sampling for Poisson-Gamma Model
#'
#' Performs Gibbs sampling for the rate parameter (lambda) of a Poisson likelihood with a Gamma prior.
#' The model assumes that the data follow a Poisson distribution, and the prior on lambda is a Gamma distribution.
#'
#' @importFrom stats rgamma
#' @param data Numeric vector of observed counts (Poisson data).
#' @param alpha_prior Prior shape parameter for the Gamma distribution.
#' @param beta_prior Prior rate parameter for the Gamma distribution.
#' @param n_iter Number of Gibbs sampling iterations.
#' @return A numeric vector of sampled lambda values.
#' @examples
#' set.seed(123)
#' data <- c(2, 4, 1, 3, 5, 2, 4, 3)
#' samples <- bayesian_poisson_gamma_R(data, alpha_prior = 2, beta_prior = 1, n_iter = 10000)
#' hist(samples, breaks = 30, main = "Posterior Samples of Lambda (Poisson Rate)")
#' @export
bayesian_poisson_gamma_cpp <- function(data, alpha_prior, beta_prior, n_iter = 10000L) {
    .Call(`_BL22204009_bayesian_poisson_gamma_cpp`, data, alpha_prior, beta_prior, n_iter)
}
#' Logistic function
#'
#' This is a logistic sigmoid function that maps input values to probabilities between 0 and 1.
#' @param x A numeric value or vector.
#' @return Logistic transformation of input x.
#' @return Logistic transformation of input x.
#' @export
logistic_cpp <- function(x) {
    .Call(`_BL22204009_logistic_cpp`, x)
}
#' Log-Likelihood for Binomial Logistic Regression
#'
#' This function computes the log-likelihood for logistic regression using the binomial distribution.
#' @param X A numeric matrix of predictors.
#' @param y A numeric vector of binary outcomes (0 or 1).
#' @param beta A numeric vector of regression coefficients.
#' @return The negative log-likelihood value.
#' @export
log_likelihood_cpp <- function(X, y, beta) {
    .Call(`_BL22204009_log_likelihood_cpp`, X, y, beta)
}
#' Gradient of the log-likelihood for Binomial Logistic Regression
#'
#' This function computes the gradient of the log-likelihood for logistic regression.
#' @param X A numeric matrix of predictors.
#' @param y A numeric vector of binary outcomes (0 or 1).
#' @param beta A numeric vector of regression coefficients.
#' @return A numeric vector of gradients for the coefficients.
#' @export
gradient_cpp <- function(X, y, beta) {
    .Call(`_BL22204009_gradient_cpp`, X, y, beta)
}
#' Binomial Logistic Regression using Gradient Descent
#'
#' This function fits a logistic regression model using gradient descent.
#' @param X A numeric matrix of predictors.
#' @param y A numeric vector of binary outcomes.
#' @param alpha A numeric value for the learning rate.
#' @param max_iter Maximum number of iterations for gradient descent.
#' @param tol Convergence tolerance.
#' @return A numeric vector of estimated coefficients.
#' @export
bino_logistic_cpp <- function(X, y, alpha = 0.01, max_iter = 1000L, tol = 1e-6) {
    .Call(`_BL22204009_bino_logistic_cpp`, X, y, alpha, max_iter, tol)
}


